### PR TITLE
Using JBoss to manage thread pool

### PR DESCRIPTION
**Pull request by abstractj**
Currently we're not using JBoss to manage our pool of threads. Should be great to do it.

### CODE REVIEW

**Comment by abstractj** [comment]
Just another observation, currently JBossThreadFactory is supported by polyglot, but not by TorqueBox.

We should discuss more about it or close this pull request

**Comment by tobias** [comment]
Crap - sorry this has sat so long my friend. I wish github had a way to remind you of pending pull requests. We'll take a look at this the next time we do any job work on Immutant.

**Comment by abstractj** [comment]
No worries my friend, I'll revisit it

**Comment by tobias** [comment]
@abstractj I'm finally doing some work on jobs today, and can take a look at this. What's the advantage of a jboss thread pool over the default quartz one?

**Pull request closed without merging**
